# Generated by Django 5.1.1 on 2024-10-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_guest_name_reservation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dinner',
            field=models.CharField(choices=[('general', 'General'), ('family', 'Family/Friends'), ('businessmeet', 'Business Meet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
    ]
