# Generated by Django 5.1.1 on 2024-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_reservation_status_alter_reservation_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='dinner_type',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
