# Generated by Django 5.1.1 on 2024-10-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
