# Generated by Django 5.1.1 on 2024-10-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_reservation_user_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
